- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: dollar
  currency: usd
  fixed: 4
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelDollar
- id: 600
  key: nubit
  currency: nbt
  fixed: 4
  fee: 0.02
  inuse: true
  type: WithdrawChannelNubit